spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: password
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
