/*
 * This file is generated by jOOQ.
 */
package com.ra.course.stackoverflow.entity.jooq;


import com.ra.course.stackoverflow.entity.jooq.tables.AccountTable;
import com.ra.course.stackoverflow.entity.jooq.tables.AnswerTable;
import com.ra.course.stackoverflow.entity.jooq.tables.CommentTable;
import com.ra.course.stackoverflow.entity.jooq.tables.QuestionTable;
import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;

import javax.annotation.processing.Generated;


/**
 * A class modelling indexes of tables of the <code>stackoverflow</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ACCOUNT_PRIMARY = Indexes0.ACCOUNT_PRIMARY;
    public static final Index ANSWER_FK_AUTHOR_ID_IN_ANSWER_IDX = Indexes0.ANSWER_FK_AUTHOR_ID_IN_ANSWER_IDX;
    public static final Index ANSWER_FK_QUESTION_ID_IN_ANSWER_IDX = Indexes0.ANSWER_FK_QUESTION_ID_IN_ANSWER_IDX;
    public static final Index ANSWER_PRIMARY = Indexes0.ANSWER_PRIMARY;
    public static final Index COMMENT_FK_ANSWER_ID_IN_COMMENT_IDX = Indexes0.COMMENT_FK_ANSWER_ID_IN_COMMENT_IDX;
    public static final Index COMMENT_FK_AUTHOR_ID_IN_COMMENT_IDX = Indexes0.COMMENT_FK_AUTHOR_ID_IN_COMMENT_IDX;
    public static final Index COMMENT_PRIMARY = Indexes0.COMMENT_PRIMARY;
    public static final Index QUESTION_FK_AUTHOR_ID_IN_QUESTION_IDX = Indexes0.QUESTION_FK_AUTHOR_ID_IN_QUESTION_IDX;
    public static final Index QUESTION_PRIMARY = Indexes0.QUESTION_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index ACCOUNT_PRIMARY = Internal.createIndex("PRIMARY", AccountTable.ACCOUNT_TABLE, new OrderField[] { AccountTable.ACCOUNT_TABLE.ID }, true);
        public static Index ANSWER_FK_AUTHOR_ID_IN_ANSWER_IDX = Internal.createIndex("fk_author_id_in_answer_idx", AnswerTable.ANSWER_TABLE, new OrderField[] { AnswerTable.ANSWER_TABLE.AUTHOR_ID }, false);
        public static Index ANSWER_FK_QUESTION_ID_IN_ANSWER_IDX = Internal.createIndex("fk_question_id_in_answer_idx", AnswerTable.ANSWER_TABLE, new OrderField[] { AnswerTable.ANSWER_TABLE.QUESTION_ID }, false);
        public static Index ANSWER_PRIMARY = Internal.createIndex("PRIMARY", AnswerTable.ANSWER_TABLE, new OrderField[] { AnswerTable.ANSWER_TABLE.ID }, true);
        public static Index COMMENT_FK_ANSWER_ID_IN_COMMENT_IDX = Internal.createIndex("fk_answer_id_in_comment_idx", CommentTable.COMMENT_TABLE, new OrderField[] { CommentTable.COMMENT_TABLE.ANSWER_ID }, false);
        public static Index COMMENT_FK_AUTHOR_ID_IN_COMMENT_IDX = Internal.createIndex("fk_author_id_in_comment_idx", CommentTable.COMMENT_TABLE, new OrderField[] { CommentTable.COMMENT_TABLE.AUTHOR_ID }, false);
        public static Index COMMENT_PRIMARY = Internal.createIndex("PRIMARY", CommentTable.COMMENT_TABLE, new OrderField[] { CommentTable.COMMENT_TABLE.ID }, true);
        public static Index QUESTION_FK_AUTHOR_ID_IN_QUESTION_IDX = Internal.createIndex("fk_author_id_in_question_idx", QuestionTable.QUESTION_TABLE, new OrderField[] { QuestionTable.QUESTION_TABLE.AUTHOR_ID }, false);
        public static Index QUESTION_PRIMARY = Internal.createIndex("PRIMARY", QuestionTable.QUESTION_TABLE, new OrderField[] { QuestionTable.QUESTION_TABLE.ID }, true);
    }
}
