/*
 * This file is generated by jOOQ.
 */
package com.ra.course.stackoverflow.entity.jooq.tables;


import com.ra.course.stackoverflow.entity.jooq.Indexes;
import com.ra.course.stackoverflow.entity.jooq.Keys;
import com.ra.course.stackoverflow.entity.jooq.Stackoverflow;
import com.ra.course.stackoverflow.entity.jooq.tables.records.AccountRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import javax.annotation.processing.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountTable extends TableImpl<AccountRecord> {

    private static final long serialVersionUID = 941972702;

    /**
     * The reference instance of <code>stackoverflow.account</code>
     */
    public static final AccountTable ACCOUNT_TABLE = new AccountTable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AccountRecord> getRecordType() {
        return AccountRecord.class;
    }

    /**
     * The column <code>stackoverflow.account.id</code>.
     */
    public final TableField<AccountRecord, Integer> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>stackoverflow.account.password</code>.
     */
    public final TableField<AccountRecord, String> PASSWORD = createField(DSL.name("password"), org.jooq.impl.SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>stackoverflow.account.account_status</code>.
     */
    public final TableField<AccountRecord, String> ACCOUNT_STATUS = createField(DSL.name("account_status"), org.jooq.impl.SQLDataType.VARCHAR(10).nullable(false), this, "");

    /**
     * The column <code>stackoverflow.account.name</code>.
     */
    public final TableField<AccountRecord, String> NAME = createField(DSL.name("name"), org.jooq.impl.SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>stackoverflow.account.email</code>.
     */
    public final TableField<AccountRecord, String> EMAIL = createField(DSL.name("email"), org.jooq.impl.SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>stackoverflow.account.phone</code>.
     */
    public final TableField<AccountRecord, String> PHONE = createField(DSL.name("phone"), org.jooq.impl.SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>stackoverflow.account.reputation</code>.
     */
    public final TableField<AccountRecord, Integer> REPUTATION = createField(DSL.name("reputation"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(DSL.inline("NULL", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * Create a <code>stackoverflow.account</code> table reference
     */
    public AccountTable() {
        this(DSL.name("account"), null);
    }

    /**
     * Create an aliased <code>stackoverflow.account</code> table reference
     */
    public AccountTable(String alias) {
        this(DSL.name(alias), ACCOUNT_TABLE);
    }

    /**
     * Create an aliased <code>stackoverflow.account</code> table reference
     */
    public AccountTable(Name alias) {
        this(alias, ACCOUNT_TABLE);
    }

    private AccountTable(Name alias, Table<AccountRecord> aliased) {
        this(alias, aliased, null);
    }

    private AccountTable(Name alias, Table<AccountRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> AccountTable(Table<O> child, ForeignKey<O, AccountRecord> key) {
        super(child, key, ACCOUNT_TABLE);
    }

    @Override
    public Schema getSchema() {
        return Stackoverflow.STACKOVERFLOW;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.ACCOUNT_PRIMARY);
    }

    @Override
    public Identity<AccountRecord, Integer> getIdentity() {
        return Keys.IDENTITY_ACCOUNT;
    }

    @Override
    public UniqueKey<AccountRecord> getPrimaryKey() {
        return Keys.KEY_ACCOUNT_PRIMARY;
    }

    @Override
    public List<UniqueKey<AccountRecord>> getKeys() {
        return Arrays.<UniqueKey<AccountRecord>>asList(Keys.KEY_ACCOUNT_PRIMARY);
    }

    @Override
    public AccountTable as(String alias) {
        return new AccountTable(DSL.name(alias), this);
    }

    @Override
    public AccountTable as(Name alias) {
        return new AccountTable(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public AccountTable rename(String name) {
        return new AccountTable(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AccountTable rename(Name name) {
        return new AccountTable(name, null);
    }

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, String, String, String, String, String, Integer> fieldsRow() {
        return (Row7) super.fieldsRow();
    }
}
